name: Checks

on:
  push

jobs:
  run_lint_and_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install the project dependencies
      run: poetry install
    - name: Run tests
      run: poetry run make test
    - name: Run lint
      run: poetry run make lint
